//! `fairlead skills sync` on a real repository: each target written in its
//! own format, a second run that changes nothing, `--check` failing on a
//! hand edit and a removed route, a person's file never overwritten, and
//! `--clean` removing only what carries the generated header.

use std::path::{Path, PathBuf};
use std::process::Command;

fn command(dir: &Path, program: &str, args: &[&str]) -> Command {
    // A clean environment, so a developer's FAIRLEAD_*, CI, git or session settings can't leak in.
    let mut cmd = Command::new(program);
    cmd.args(args).current_dir(dir).env_clear();
    for keep in ["PATH", "SYSTEMROOT"] {
        if let Some(value) = std::env::var_os(keep) {
            cmd.env(keep, value);
        }
    }
    cmd.env("HOME", dir).env("GIT_CONFIG_NOSYSTEM", "1");
    cmd
}

fn fairlead(dir: &Path, args: &[&str]) -> (i32, String) {
    let out = command(dir, env!("CARGO_BIN_EXE_fairlead"), args)
        .output()
        .unwrap();
    let text =
        String::from_utf8_lossy(&out.stdout).into_owned() + &String::from_utf8_lossy(&out.stderr);
    (out.status.code().unwrap_or(-1), text)
}

const FORMS: &str = r#"
[[skills.routes]]
skill = "skills/forms/SKILL.md"
paths = ["src/forms/**"]
"#;

const MONEY: &str = r#"
[[skills.routes]]
skill = "skills/money/SKILL.md"
paths = ["src/money.ts", "src/pay/**"]
"#;

const STYLE: &str = r#"
[[skills.routes]]
skill = ".claude/skills/style/SKILL.md"
always = true
"#;

const STYLE_SKILL: &str = "---\nname: style\ndescription: House style.\n---\nShort sentences.\n";

fn skill(dir: &Path, at: &str, name: &str, description: &str) {
    let d = dir.join(at);
    std::fs::create_dir_all(&d).unwrap();
    std::fs::write(
        d.join("SKILL.md"),
        format!("---\nname: {name}\ndescription: {description}\n---\nHow to.\n"),
    )
    .unwrap();
}

/// Two skills under `skills/`, one already in `.claude/skills`, all routed.
fn repo(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("fairlead-sync-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    assert!(command(&dir, "git", &["init", "-q", "-b", "main"])
        .output()
        .unwrap()
        .status
        .success());
    std::fs::write(dir.join("fairlead.toml"), format!("{FORMS}{MONEY}{STYLE}")).unwrap();
    skill(&dir, "skills/forms", "forms", "How forms validate.");
    skill(&dir, "skills/money", "money", "Amounts are integers.");
    std::fs::create_dir_all(dir.join("skills/forms/scripts")).unwrap();
    std::fs::write(dir.join("skills/forms/scripts/check.sh"), "true\n").unwrap();
    std::fs::create_dir_all(dir.join(".claude/skills/style")).unwrap();
    std::fs::write(dir.join(".claude/skills/style/SKILL.md"), STYLE_SKILL).unwrap();
    dir
}

fn read(dir: &Path, path: &str) -> String {
    std::fs::read_to_string(dir.join(path)).unwrap_or_else(|e| panic!("{path}: {e}"))
}

#[test]
fn sync_writes_every_target_in_its_format_and_a_second_sync_changes_nothing() {
    let dir = repo("write");
    let (code, out) = fairlead(&dir, &["skills", "sync"]);
    assert_eq!(code, 0, "{out}");
    for path in [
        ".claude/skills/forms/SKILL.md",
        ".agents/skills/forms/SKILL.md",
        ".cursor/rules/forms.mdc",
        ".claude/skills/money/SKILL.md",
        ".agents/skills/money/SKILL.md",
        ".cursor/rules/money.mdc",
        ".agents/skills/style/SKILL.md",
        ".cursor/rules/style.mdc",
    ] {
        assert!(
            out.contains(&format!("wrote {path} (from ")),
            "{path}: {out}"
        );
    }
    let copy = read(&dir, ".agents/skills/forms/SKILL.md");
    assert!(
        copy.starts_with(
            "---\n# Generated by fairlead skills sync from skills/forms/SKILL.md; edit that file, not this one.\nname: forms\n"
        ),
        "{copy}"
    );
    assert!(copy.ends_with("---\nHow to.\n"), "{copy}");
    let money = read(&dir, ".cursor/rules/money.mdc");
    assert!(
        money.contains("description: \"Amounts are integers.\"\n"),
        "{money}"
    );
    assert!(
        money.contains("globs: src/money.ts,src/pay/**\nalwaysApply: false\n"),
        "{money}"
    );
    let style = read(&dir, ".cursor/rules/style.mdc");
    assert!(
        style.contains("alwaysApply: true\n---\nShort sentences.\n"),
        "{style}"
    );
    assert!(
        out.contains("not copied: skills/forms/scripts/ (sync copies SKILL.md only)"),
        "{out}"
    );

    // The source already in .claude/skills is the Claude Code copy: nothing is written there.
    assert_eq!(read(&dir, ".claude/skills/style/SKILL.md"), STYLE_SKILL);
    assert!(!out.contains("wrote .claude/skills/style"), "{out}");
    let mut claude: Vec<String> = std::fs::read_dir(dir.join(".claude/skills"))
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .collect();
    claude.sort();
    assert_eq!(claude, ["forms", "money", "style"]);

    let (code, again) = fairlead(&dir, &["skills", "sync"]);
    assert_eq!(code, 0, "{again}");
    assert!(!again.contains("wrote"), "{again}");
    assert_eq!(again.matches("unchanged ").count(), 8, "{again}");
    let (code, checked) = fairlead(&dir, &["skills", "sync", "--check"]);
    assert_eq!(code, 0, "{checked}");
    assert!(checked.contains("skills in sync: 8 file(s)"), "{checked}");
}

#[test]
fn check_fails_on_a_hand_edit_and_on_a_removed_route_and_sync_removes_the_orphans() {
    let dir = repo("check");
    let (code, out) = fairlead(&dir, &["skills", "sync", "--check"]);
    assert_eq!(code, 1, "nothing is written yet: {out}");
    assert!(out.contains("missing .cursor/rules/forms.mdc"), "{out}");
    assert!(!dir.join(".cursor").exists(), "--check writes nothing");
    assert_eq!(fairlead(&dir, &["skills", "sync"]).0, 0);

    let edited = dir.join(".agents/skills/forms/SKILL.md");
    let text = read(&dir, ".agents/skills/forms/SKILL.md") + "A hand edit.\n";
    std::fs::write(&edited, &text).unwrap();
    let (code, out) = fairlead(&dir, &["skills", "sync", "--check"]);
    assert_eq!(code, 1, "{out}");
    assert!(
        out.contains(
            "stale .agents/skills/forms/SKILL.md: differs from what skills/forms/SKILL.md gives"
        ),
        "{out}"
    );
    assert_eq!(
        std::fs::read_to_string(&edited).unwrap(),
        text,
        "--check writes nothing"
    );
    let (_, doctor) = fairlead(&dir, &["doctor"]);
    assert!(doctor.contains("skills sync: 1 problem(s)"), "{doctor}");
    assert_eq!(fairlead(&dir, &["skills", "sync"]).0, 0);
    let (_, doctor) = fairlead(&dir, &["doctor"]);
    assert!(!doctor.contains("skills sync:"), "{doctor}");

    std::fs::write(dir.join("fairlead.toml"), format!("{FORMS}{STYLE}")).unwrap();
    let (code, out) = fairlead(&dir, &["skills", "sync", "--check"]);
    assert_eq!(code, 1, "{out}");
    for gone in [
        ".claude/skills/money/SKILL.md",
        ".agents/skills/money/SKILL.md",
        ".cursor/rules/money.mdc",
    ] {
        assert!(
            out.contains(&format!("orphaned {gone}: no route writes it")),
            "{out}"
        );
    }
    let (code, out) = fairlead(&dir, &["skills", "sync"]);
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("removed .cursor/rules/money.mdc"), "{out}");
    assert!(
        !dir.join(".claude/skills/money").exists(),
        "the empty skill directory goes too"
    );
    assert!(!dir.join(".agents/skills/money").exists());
    assert!(dir.join(".cursor/rules/forms.mdc").exists());
    assert_eq!(fairlead(&dir, &["skills", "sync", "--check"]).0, 0);
}

#[test]
fn a_hand_written_file_at_a_target_path_is_a_conflict_and_left_alone() {
    let dir = repo("conflict");
    std::fs::create_dir_all(dir.join(".cursor/rules")).unwrap();
    std::fs::write(dir.join(".cursor/rules/forms.mdc"), "My own rule.\n").unwrap();
    let (code, out) = fairlead(&dir, &["skills", "sync"]);
    assert_eq!(code, 1, "{out}");
    assert!(
        out.contains(
            "conflict .cursor/rules/forms.mdc: exists without the generated header; left alone"
        ),
        "{out}"
    );
    assert_eq!(read(&dir, ".cursor/rules/forms.mdc"), "My own rule.\n");
    assert!(
        dir.join(".cursor/rules/money.mdc").exists(),
        "the rest is still written"
    );
    let (code, out) = fairlead(&dir, &["skills", "sync", "--check"]);
    assert_eq!(code, 1, "{out}");
    assert!(out.contains("conflict .cursor/rules/forms.mdc"), "{out}");
}

#[test]
fn clean_removes_only_files_that_carry_the_generated_header() {
    let dir = repo("clean");
    assert_eq!(fairlead(&dir, &["skills", "sync"]).0, 0);
    std::fs::write(
        dir.join(".cursor/rules/mine.mdc"),
        "---\nalwaysApply: true\n---\nMine.\n",
    )
    .unwrap();
    skill(&dir, ".agents/skills/mine", "mine", "A person's skill.");
    let (code, out) = fairlead(&dir, &["skills", "sync", "--clean"]);
    assert_eq!(code, 0, "{out}");
    assert_eq!(out.matches("removed ").count(), 8, "{out}");
    for kept in [
        ".cursor/rules/mine.mdc",
        ".agents/skills/mine/SKILL.md",
        ".claude/skills/style/SKILL.md",
        "skills/forms/SKILL.md",
    ] {
        assert!(dir.join(kept).exists(), "{kept} has no header: {out}");
    }
    assert!(!dir.join(".claude/skills/forms").exists(), "{out}");
    assert!(!dir.join(".cursor/rules/forms.mdc").exists(), "{out}");
    let (code, out) = fairlead(&dir, &["skills", "sync", "--clean"]);
    assert_eq!(code, 0, "{out}");
    assert!(out.contains("nothing to clean"), "{out}");
}
